name: CMake

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    # TODO: The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    #       You can convert this to a matrix build if you need cross-platform coverage.
    #       See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.2.3'

      - name: Install Blast
        run: sudo apt-get install -y ncbi-blast+

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Unit Tests
        working-directory: ${{github.workspace}}/build
        run: ./BandageTests

      - name: CLI Tests
        working-directory: ${{github.workspace}}/tests
        run: ./bandage_command_line_tests.sh ${{github.workspace}}/build/Bandage
