name: GitHub Release

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - "VERSION.txt"
      - ".github/workflows/release.yml"

# Cancel any preceding run on the pull request.
concurrency:
  group: release-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    if: ${{ github.repository == 'asl/Bandage-NG' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        run: |
          VERSION="$(cat VERSION.txt)"
          TAG="v$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Check if tag exists
        id: check_tag
        run: |
          TAG="${{ env.TAG }}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists, skipping release creation."
            echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            echo "Tag $TAG does not exist."
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Release
        if: steps.check_tag.outputs.tag_exists == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ env.TAG }}',
              sha: context.sha
            })        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
